config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  #root to: "home#index"
  root to: "experiments#index"

  resources :chart_queries, only: [:create, :destroy]

  resources :experiments do
    member do
      get 'copy'
      get 'to_debug'
      get 'to_edit'
      get 'to_open'
      get 'to_closed'
    end
  end

  # API routes
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post '/participants', to: 'experiment_data#register_participant'#, as: 'api_registration'
      post '/experiments/parts/:part_id/data', to: 'experiment_data#create'#, as: 'api_test_data'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.slim
h3 Home page.
p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Et harum quidem rerum facilis est et expedita distinctio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nullam at arcu a est sollicitudin euismod. Aliquam erat volutpat. Etiam commodo dui eget wisi. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Phasellus rhoncus. Donec quis nibh at felis congue commodo. Maecenas libero.

p Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Mauris metus. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Vivamus ac leo pretium faucibus. Fusce nibh. Aenean placerat. Etiam bibendum elit eget erat. Mauris dictum facilisis augue.

- if user_signed_in?
    = link_to 'Create test', new_experiment_path, class: 'button button-primary'