config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  #root to: "home#index"
  root to: "experiments#index"

  resources :chart_queries, only: [:create, :destroy]

  resources :experiments do
    member do
      get 'copy'
      get 'to_debug'
      get 'to_edit'
      get 'to_open'
      get 'to_closed'
    end
  end

  # API routes
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post '/participants', to: 'experiment_data#register_participant'#, as: 'api_registration'
      post '/experiments/parts/:part_id/data', to: 'experiment_data#create'#, as: 'api_test_data'
    end
  end
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  self.per_page = 10

  has_many :parts, class_name: 'Experiment::Part', dependent: :destroy, autosave: true
  has_many :data, through: :parts, source: :data
  has_many :variables, through: :parts
  has_many :json_data, class_name: 'Experiment::JsonDatum', dependent: :destroy
  has_many :chart_queries, dependent: :destroy
  has_many :participants, dependent: :destroy
  belongs_to :user
  # Recursive association for action "Copy"
  has_many :children, class_name: 'Experiment', foreign_key: "copy_parent_id"

  accepts_nested_attributes_for :parts, reject_if: :all_blank, allow_destroy: true

  # VALIDATIONS
  validates_presence_of :name, :parts
  validates :name, uniqueness: true

  validates_associated :parts

  # FILTERS (before/after)
  before_save :generate_access_token
  after_save :cascade_save_parts

  # SCOPES
  default_scope { order(created_at: :desc) }

  # Enable nested copy
  amoeba do
    enable
    nullify :access_token
    include_association :parts
    set state: :edit

    customize(lambda { |original, new_record|
      children_count = original.children.count + 1

      new_record.copy_parent_id = original.id
      new_record.name += " (#{children_count})"
    })
  end

  ALL_EVENTS = [:edit, :debug, :open, :closed]

  # Define states transitions
  state_machine :state, initial: :edit do
    event :to_debug do
      transition edit: :debug
    end

    event :to_edit do
      transition debug: :edit
    end

    event :to_open do
      transition debug: :open
    end

    event :to_closed do
      transition open: :closed
    end

    after_transition on: :to_edit, do: :clear_data
  end

  def generate_access_token
    self.access_token = "#{self.name.parameterize}"
  end

  def cascade_save_parts
    self.parts.each(&:save) if valid?
  end

  def clear_data
    self.parts.each(&:clear_data)
  end

  # def validate_uniq_name
  #   where(self.name.parameterize)
  # end

  def as_json(options)
    super(
      root: true,
      except: [:id, :user_id, :copy_parent_id, :created_at, :updated_at],
      include: {
        parts: {
          only: [:name, :access_token, :description],
          methods: :design,
          include: {
            variables: {
              only: [:name, :log_transform, :repetition_count],
              methods: [:type, :data_to_json]
            }
          }
        }
      }
    )
  end

end

app/models/experiment/datum.rb
class Experiment::Datum < ApplicationRecord
  belongs_to :variable, class_name: 'Experiment::Variable'
  belongs_to :participant
  belongs_to :target, polymorphic: true

  scope :active, -> { where(delete_reason: nil) }

end

app/models/experiment/json_datum.rb
class Experiment::JsonDatum < ApplicationRecord
    self.table_name = "experiment_json_data"

    belongs_to :experiment
    belongs_to :part, class_name: 'Experiment::Part'
end

app/models/experiment/part.rb
class Experiment::Part < ApplicationRecord
  belongs_to :experiment
  has_many :variables, class_name: 'Experiment::Variable', dependent: :destroy
  has_many :data, through: :variables, source: :values
  has_many :json_data, class_name: 'Experiment::JsonDatum', dependent: :destroy

  accepts_nested_attributes_for :variables, reject_if: :all_blank, allow_destroy: true

  as_enum :design, %i{within_subject between_subject}, source: :design_type

  validates_presence_of :name, :variables
  validates :name, uniqueness: { scope: :experiment, message: 'should be unique in Experiment context.' }
  validates :repetition_count, numericality: { greater_than: 0 }

  validates_associated :variables

  before_save :generate_access_token

  # enable nested copy
  amoeba do
    enable
    nullify :access_token
    include_association :variables
  end

  def to_s
    name
  end

  def variables_to_s
    variables.map(&:to_s).join(', ')
  end

  def generate_access_token
    self.access_token = "#{experiment.access_token}-#{name.parameterize}"
  end

  def clear_data
    self.variables.each(&:clear_data)
    self.json_data.delete_all
  end

  def as_json(options)
    super(except: [:id, :experiment_id, :created_at, :updated_at], include: :variables)
  end

end

app/models/experiment/variable.rb
class Experiment::Variable < ApplicationRecord
  belongs_to :part, class_name: 'Experiment::Part'
  has_many :values, class_name: 'Experiment::Datum', dependent: :destroy

  validates_presence_of :name, :data_type
  validates :name, uniqueness: { scope: :part, message: "should be unique in Part context." }


  STRING = 0
  LONG = 1
  DOUBLE = 2

  TYPES = {
    string: STRING,
    long: LONG,
    double: DOUBLE
  }.freeze

  LOG_TRANSFORM = 0
  NORMAL_DIST = 1
  BINOMIAL_DIST = 2

  METHODS = {
    log_transformation: LOG_TRANSFORM,
    normal_distribution: NORMAL_DIST,
    binomial_distribution: BINOMIAL_DIST
  }.freeze

  as_enum :type, TYPES, source: :data_type
  as_enum :method, METHODS, source: :calculation_method

  #  ---- SCOPES ----
  default_scope { order(id: :asc) }
  scope :not_strings, -> { where.not(data_type: STRING) }
  scope :strings, -> { where(data_type: STRING) }

  def to_s
    name
  end

  def clear_data
    self.values.update_all(delete_reason: 'test')
  end

  # we want to work only with ACTIVE data (without "delete_reason")
  def data
    values.active.map { |value| value.target.value }
  end

  # helping function for JSON export
  # we want to export ALL data values
  def data_to_json
    values.map { |value| { value: value.target.value, delete_reason: value.delete_reason } }
  end

end

app/controllers/experiments_controller.rb
require 'histogram/array'

class ExperimentsController < ApplicationController
  allowed_ghost_actions [:to_debug, :to_edit, :to_open, :to_closed]
  before_action :set_experiment, except: [:new, :create, :index]
  before_action :is_user_owner, except: [:new, :create, :index]
  before_action :is_editable, only: [:edit, :update]
  add_breadcrumb I18n.t(:experiment_plural), :experiments_path


  def colors
    [
      "rgba(20,220,220,0.3)",
      "rgba(30,240,120,0.3)",
      "rgba(40,120,200,0.3)",
      "rgba(120,220,220,0.3)",
      "rgba(20,220,220,0.3)"
    ]
  end

  # GET /experiments
  # GET /experiments.json
  def index
    #@experiments = Experiment.page(params[:page]) #this returns experiments of all users
    @experiments = current_user.experiments.page(params[:page])
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    add_breadcrumb "#{@experiment.name}", @experiment

    # boxplot form preparations
    prepare_boxplot_form

    # Grouped select options for all variables (grouped by part)
    @grouped_variables = {}
    @experiment.parts.each do |part|
      @grouped_variables[part.name] = part.variables.pluck(:name, :id)
    end

    @string_var_ids = @experiment.variables.strings.pluck(:id)

    # Histogram chart for check data
    prepare_data_for_var(params[:chart_variable]) if params[:chart_variable].present?

    # Boxplots hash
    @boxplots = {}

    @experiment.chart_queries.each do |query|
      @max = 0
      plot_data,raw_data,header_row = prepare_boxplot_data(query)

      # Boxplot chart
      @boxplots[query.name] = {
        id: query.id,
        name_code: query.name.parameterize,
        data: plot_data,
        max: (@max + 50).round,
        raw_data: raw_data,
        header_row: header_row
      }
    end

    #
    respond_to do |format|
      format.html {}
      # Download as json
      format.json {
        file_name = "#{@experiment.name.parameterize.underscore}"
        flash[:notice] = 'Experiment was successfully exported.'
        content = @experiment.to_json
        send_data content, filename: "#{file_name}.json"
      }
    end
  end

  # GET /experiments/new
  # Shows form to create new experiment
  def new
    #@experiment = Experiment.new(user: current_user)
    @experiment = current_user.experiments.build
    @experiment.parts.build
    add_breadcrumb t(:new_experiment_breadcrumb), new_experiment_path
  end

  # GET /experiments/1/edit
  def edit
    add_breadcrumb "#{@experiment.name}", @experiment
    add_breadcrumb t(:edit_breadcrumb), edit_experiment_path(@experiment)
  end

  # POST /experiments
  # POST /experiments.json
  def create
    #@experiment = Experiment.new(experiment_params)
    #@experiment.user = current_user
    @experiment = current_user.experiments.build(experiment_params)
    @experiment.number_of_parts = @experiment.parts.size

    #respond_to do |format|
      if @experiment.save
        #format.html {
          flash[:notice] = 'Experiment was successfully created.'
          redirect_to @experiment
        #}
        #format.json { render :show, status: :created, location: @experiment }
      else
        #format.html { 
          render :new 
        #}
        #format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    @experiment.attributes = experiment_params
    @experiment.number_of_parts = 0
    for part in @experiment.parts
      @experiment.number_of_parts += 1 if part._destroy == false
    end
    #respond_to do |format|
      #if @experiment.update(experiment_params)
      if @experiment.save()
        #format.html {
          flash[:notice] = 'Experiment was successfully updated.'
          redirect_to @experiment
        #}
        #format.json { render :show, status: :ok, location: @experiment }
      else
        #format.html { 
          render :edit 
        #}
        #format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    #end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    #respond_to do |format|
      #format.html {
        flash[:notice] = 'Experiment was successfully destroyed.'
        redirect_to experiments_url
      #}
      #format.json { head :no_content }
    #end
  end

  # POST /experiments/1/copy
  # POST /experiments/1/copy.json
  def copy
    new_experiment = @experiment.amoeba_dup

    #respond_to do |format|
      if new_experiment.save
        #format.html {
          flash[:notice] = 'Experiment was successfully duplicated.'
          redirect_to new_experiment
        #}
        #format.json { render :show, status: :ok, location: new_experiment }
      else
        #format.html {
          flash[:notice] = new_experiment.errors.full_messages.join(', ')
          redirect_to @experiment
        #}
        #format.json { render json: new_experiment.errors, status: :unprocessable_entity }
      end
    #end
  end

  #
  # If the action exists and is included in the allowed actions then is dynamically loaded.
  #
  def action_missing(name)
    begin
      self.send name
    rescue
      super
    end
  end

  def change_state(transition)
    if @experiment.send transition
      flash[:notice] = 'Experiment state was successfully changed.'
    else
      flash[:alert] = 'Invalid experiment state transition.'
    end
    redirect_to @experiment
  end

  #
  # As the action will call the method, it's necessary to handle the behavior if this method doesn't exist.
  #
  def method_missing(name, *args, &block)
    return change_state(name) if respond_to?(name, true)
    super
  end

  private

    def prepare_boxplot_form
      @definition = ChartQuery.new(experiment_id: @experiment.id)
      @target_vars = @experiment.variables.not_strings.pluck(:name).uniq
      @filter_vars = @experiment.variables.strings.pluck(:name).uniq
      @calculate_methods = Experiment::Variable::METHODS.map{ |key, value| [t(key), value] }

      @filter_values = {}

      @filter_vars.each do |variable_name|
        @filter_values[variable_name] = @experiment.json_data
                                                   .pluck("data ->> '#{variable_name}'")
                                                   .compact
                                                   .uniq
        @filter_values[variable_name] << "all"
      end
    end

    def prepare_data_for_var(variable_id)
      variable = Experiment::Variable.find(variable_id)
      # can't work without data
      if variable.data.blank?
        return
      end
      if variable.string?
        @raw_data = variable.data
        pairs = @raw_data.group_by(&:itself).map { |k,v| [k, v.count] }.to_h
      else
        @raw_data = variable.long? ? variable.data.map(&:to_i) : variable.data.map(&:to_f)
        settings = { bin_boundary: :min }
        settings[:bin_width] = params[:step_size].to_i if params[:step_size].present?
        settings[:min] = params[:min].to_i if params[:min].present?
        settings[:max] = params[:max].to_i if params[:max].present?
        bar_count = params[:bar_count].to_i if params[:bar_count].present?
        begin
          x,y = @raw_data.histogram(bar_count, settings)
          x.map!{|item| item.round(3)}
          pairs = x.zip(y)
        rescue
          # handle error
          flash[:error] = 'Something was wrong...try again'
          return redirect_to @experiment
        end
      end
      # histogram plot
      @histogram_data = [variable.name]
      @histogram_data << pairs.map { |value, count| { x: value, y: count } }
    end

    def prepare_boxplot_data(query)
      target_var = Experiment::Variable.where(name: query.target_variable).first
      filter_var = Experiment::Variable.where(name: query.filter_variable).first

      x_labels = query.filter_variable_values.reject(&:blank?)
                                               .map { |value| "#{filter_var.name} #{value}" }

      return if x_labels.empty?

      raw_data = {}

      # labels from filter_variable
      boxplot_data = { labels: x_labels, datasets: [] }
      # for color
      i = 0

      @experiment.parts.each do |part|
        next unless part.variables.pluck(:name).include? target_var.name

        means,uppers,lowers,medians,orig_means = calculate_means_for(
                                                   part,
                                                   target_var,
                                                   filter_var,
                                                   query.filter_variable_values,
                                                   query.calculate_method
                                                 )
        @max = uppers.max if @max < uppers.max

        boxplot_data[:datasets] << {
                            label: part.name, # legend name => part name
                            backgroundColor: colors[i],
                            errorColor: 'rgba(128,128,128,0.8)',
                            errorStrokeWidth: 1,
                            errorCapWidth: 0.5,
                            data:  means,
                            uppers: uppers,
                            lowers: lowers
                          }
        i += 1

        raw_data[part.name] = []

        # tmp_ar = []
        # means.size.times do |ind|
        #   tmp_ar << "#{means[ind]}(#{lowers[ind]}, #{uppers[ind]})"
        # end

        means.size.times do |ind|
          raw_data[part.name] << {
            geo_mean: means[ind],
            lower: lowers[ind],
            upper: uppers[ind],
            median: medians[ind],
            orig_mean: orig_means[ind]
          }
        end

      end

      [boxplot_data, raw_data, x_labels]
    end

    def calculate_means_for(part, target_var, filter_var, filter_var_values, calculate_method)
      means = []
      orig_means = []

app/helpers/experiments_helper.rb
module ExperimentsHelper

  def prefill_variables
    {
      time: {
              name: t(:variable_time),
              data_type: Experiment::Variable::DOUBLE,
              calculation_method: Experiment::Variable::LOG_TRANSFORM
            },
      error: {
               name: t(:variable_error),
               data_type: Experiment::Variable::LONG,
               calculation_method: Experiment::Variable::BINOMIAL_DIST
             },
      scale: {
               name: t(:variable_scale),
               data_type: Experiment::Variable::LONG,
               calculation_method: Experiment::Variable::NORMAL_DIST
             },
      filter: {
                name: t(:variable_filter),
                data_type: Experiment::Variable::STRING,
                calculation_method: nil
              }
    }
  end

  def is_need_prefill(object, field)
    object.new_record? && object.send(field).nil?
  end

  def object_value(object, field, prefill)
    is_need_prefill(object, field) ? prefill[field] : object.send(field)
  end

end

app/views/experiments/_chart_settings.html.slim
.popover.fade.top.in role="tooltip"
  .arrow style="left: 50%;"
  h3.popover-title Chart Settings
  .popover-content
    .legend-options
      label.form-check-label
        input.show-legend type="checkbox" checked="checked"
        | Show legend
      .details
        label Position
        select.position
          option value='top' Top
          option value='bottom' Bottom
    .grid-options
      label.form-check-label
        input.show-x-grid type='checkbox' checked="checked"
        | Show X axes
      label.form-check-label
        input.show-y-grid type='checkbox' checked="checked"
        | Show Y axes
    .max-tick.flex-row.baseline
      label Y axe step size
      input.y-step-size type='number'


  javascript:
    $(function() {
      var parentId = "#{parent_id}";
      var parentContainer = $('#'+parentId);
      var canvasId = "#{chart_id}";
      var canvasObj = $('#'+canvasId);
      var chartId = canvasObj.data('chart-id');
      var chart = Chart.instances[chartId];

      var showLegend = parentContainer.find('.show-legend');
      var showXGrid = parentContainer.find('.show-x-grid');
      var showYGrid = parentContainer.find('.show-y-grid');
      var showTitle = parentContainer.find('.show-title');
      var downloadButton = parentContainer.find('.download');
      var settingsButton = parentContainer.find('.settings');
      var popoverCard = parentContainer.find('.popover');
      var selectPosition = parentContainer.find('.position');
      var titleInput = parentContainer.find('.title-text');
      var yStepSize = parentContainer.find('.y-step-size');

      showXGrid.click(function(e) {
        chart.options.scales.xAxes[0].gridLines.display = $(this).is(":checked");
        chart.update();
      });

      showYGrid.click(function(e) {
        chart.options.scales.yAxes[0].gridLines.display = $(this).is(":checked");
        chart.update();
      });

      function downloadChart() {
        var url = chart.toBase64Image();
        download(url, canvasId+'.png');
      }

      downloadButton.click(downloadChart);

      showLegend.click(function(e) {
        chart.options.legend.display = $(this).is(":checked");
        chart.update();
      });

      selectPosition.change(function(e) {
        chart.options.legend.position = $(this).val();
        chart.update();
      });

      showTitle.click(function(e) {
        chart.options.title.display = $(this).is(":checked");
        chart.update();
      });

      titleInput.on('keyup', function(e) {
        chart.options.title.text = $(this).val();
        chart.update();
      });

      settingsButton.click(function(e) {
        popoverCard.toggle();
      });

      yStepSize.on('keyup', function(e) {
        chart.options.scales.yAxes[0].ticks.stepSize = Number($(this).val());
        chart.update();
      });

      // Toggle for raw data
      $('#data-toggle-for-'+canvasId).click(function(){
        $('#raw-data-for-'+canvasId).toggle();
      });

    });

app/views/experiments/_form.html.slim
= form_for @experiment do |f|
  - if @experiment.errors.any?
    ul.errors
      - @experiment.errors.full_messages.each do |message|
        li = message

  .row
    .four.columns
      .field
        = f.label :name
        = f.text_field :name, class: 'u-full-width'
    .eight.columns
      .field
        = f.label :description
        = f.text_area :description, rows: 35, class: 'u-full-width', placeholder: 'Write your experiment description here...'

  .row
    .four_columns
      .field 
        = f.label :timeout
        = f.number_field :timeout, class: 'u-full-width' , placeholder: 'Time in minutes after which the participant is discarded if s/he doesn\'t finish the experiment.'

  h5 = t(:part_plural)
  #experiment_parts
    = f.fields_for :parts do |part|
      = render 'part_fields', f: part
    .links
      = link_to_add_association t(:add_part), f, :parts

  br
  .actions
    = f.submit class: 'button-primary'

app/views/experiments/_part_fields.slim
.nested-fields.part
  .row
    .four.columns
      .field
        = f.label :name
        = f.text_field :name, class: 'u-full-width'
      .field
        = f.label :design_type
        = f.select :design, enum_option_pairs(Experiment::Part, :design), {}, {class: 'u-full-width'}
      .field
        = f.label :repetition_count
        = f.text_field :repetition_count, type: "number", min: 1, max: 100, class: 'u-full-width'
    .eight.columns
      .field
        = f.label :description
        = f.text_area :description, class: 'u-full-width', placeholder: 'Write your part description here...'

  = link_to_remove_association(f) do
    == material_icon.cancel.md_24

  h5 = t(:variable_plural)
  #test_variables
    = f.fields_for :variables do |variable|
      = render 'variable_fields', f: variable, prefill: {}
    .add-link
      span.margin = t(:add_label)
      - prefill_variables.keys.each do |key|
        = link_to_add_association t("variable_#{key}"), f, :variables, render_options: { locals: { prefill: prefill_variables[key] } }
      = link_to_add_association t("variable_custom"), f, :variables, render_options: { locals: { prefill: {} } }




javascript:
  window.prefillValues = #{{ JSON.dump(prefill_variables) }}

app/views/experiments/_variable_fields.slim
.nested-fields.variable
  .field
    = f.label :variable_name
    = f.text_field :name, class: 'u-full-width', value: object_value(f.object, :name, prefill)
  .field
    = f.label :data_type
    = f.select :data_type, enum_option_pairs(Experiment::Variable, :type, true),{ selected: object_value(f.object, :data_type, prefill) }, { class: 'u-full-width' }
  - if prefill[:name] == t(:variable_error) || f.object.positive_value.present?
    .field
      .flex-row
        = f.label :positive_value
        span title=t(:positive_value_help) == material_icon.help_outline.md_18
      = f.text_field :positive_value, class: 'u-full-width', value: object_value(f.object, :positive_value, prefill), required: true
  .field
    = f.label :calculation_method
    = f.select :calculation_method, enum_option_pairs(Experiment::Variable, :method, true), { selected: object_value(f.object, :calculation_method, prefill), prompt: t(:prompt_label), class: 'u-full-width'}

  = link_to_remove_association(f) do
    == material_icon.cancel.md_24

app/views/experiments/edit.html.slim
== render 'form'

app/views/experiments/index.html.slim
.absolute-right
  = link_to t(:label_new_experiment), new_experiment_path, class: 'button button-primary'

- if @experiments.blank?
    p.no-content No content.
- else
    table.u-full-width
      thead
        tr
          th.text-center Name
          th.text-center # of Parts
          th.text-center State
          th.text-center Show
          th.text-center Edit
          th.text-center Delete
      tbody
        - @experiments.each do |experiment|
          tr
            td = experiment.name
            td = experiment.number_of_parts
            td.text-center = "#{experiment.state.upcase}"
            td.text-center = link_to material_icon.visibility.md_24, experiment
            td.text-center class=('disabled' unless experiment.edit?)
              = link_to material_icon.edit.md_24, edit_experiment_path(experiment)
            td.text-center = link_to material_icon.delete.md_24, experiment, data: { confirm: 'Are you sure?' }, method: :delete

    .page_info
      = page_entries_info @experiments
    = will_paginate @experiments

app/views/experiments/new.html.slim
== render 'form'

app/views/experiments/show.html.slim
.absolute-right.flex-row
  = link_to material_icon.get_app.md_24, experiment_path(@experiment, format: :json), title: t(:export_title)
  = link_to material_icon.content_copy.md_24, copy_experiment_path(@experiment), title: t(:duplicate_title)
  = link_to material_icon.edit.md_24, edit_experiment_path(@experiment), title: t(:edit_title) if @experiment.edit?
  = link_to material_icon.delete.md_24, @experiment, data: { confirm: 'Are you sure?' }, method: :delete, title: t(:delete_title)


#timeline
  ul
    - Experiment::ALL_EVENTS.each do |event|
      li
        - if @experiment.send("#{event}?")
          span(class='active') = t("to_#{event}")
        - else
          = link_to t("to_#{event}"), { controller: 'experiments', action: "to_#{event}", id: @experiment.id }, class: !@experiment.send("can_to_#{event}?") ? 'disabled' : '', title: t("#{event}_description")

p.small
  = @experiment.description

.card-footer
  label = t(:access_token)
  input.u-full-width type="text" value=@experiment.access_token readonly="true"

.card-footer
  label = t(:timeout)
  input.u-full-width type="number" value=@experiment.timeout readonly="true"


h5 = t(:part_plural)

//.flex-row.between

- @experiment.parts.each do |part|
  .part.card.col
    .card-header
      strong = part.name
    .card-body
      p.small
        = part.description
      p
        strong = t(:variable_plural)
        = ": [ #{part.variables_to_s} ]"
      p
        strong = t(:design_type)
        = ": #{te(part, :design)}"
      p
        strong = t(:repetition_count)
        = ": #{part.repetition_count}"
      label = t(:access_token)
      input.u-full-width type="text" value=part.access_token readonly="true"
br

h5 = t(:values)

- if @experiment.json_data.present?

  //  ------------------ HISTOGRAM FORM -----------------------------
  p.text-muted = t(:histogram_label)
  = form_tag(@experiment, method: :get, class: 'query-form flex-row items-end', id: 'histogram-form') do
    div
      label = t(:variable)
      = select_tag('chart_variable', grouped_options_for_select(@grouped_variables, params[:chart_variable], prompt: t(:prompt_label)), required: true)
    .additional-settings
      label = t(:step_size)
      = number_field_tag('step_size', params[:step_size], min: 1, class: 'number-field')
    .additional-settings
      label = t(:bar_count)
      = number_field_tag('bar_count', params[:bar_count], min: 1, class: 'number-field')
    .additional-settings
      label = t(:min)
      = number_field_tag('min', params[:min], min: 0, class: 'number-field')
    .additional-settings
      label = t(:max)
      = number_field_tag('max', params[:max], min: 0, class: 'number-field')

    = submit_tag('Show', name: nil, class: 'button-primary')

  javascript:
    var stringVarIds = #{{ JSON.dump(@string_var_ids) }}
    function disableInputs() {
      $('.additional-settings > input').prop('disabled', stringVarIds.includes(Number($("#chart_variable").val())));
    }

    $('#chart_variable').on('change', disableInputs);
    disableInputs();

  // ----------------  HISTOGRAM -------------
  - if @histogram_data
    #histogram-container.card
      == render partial: 'chart_settings', locals: { parent_id: 'histogram-container', chart_id: 'histogram' }
      .card-header
        strong Histogram
        .card-actions
          a.settings Settings
          a.download Save
      .card-body style="position: relative; height:300px;"

    button#raw-data-hist-toggle = t(:raw_data)
    #histogram-raw-data style="display: none;"
      pre = "#{@histogram_data[0]} = #{@raw_data}"
      strong = "#{t(:total_count)}: #{@raw_data.size}"


    javascript:
      var histogramData = #{{ JSON.dump(@histogram_data) }};
      if (histogramData) {
        drawHistogram(histogramData[0], histogramData[1]);
      }

      $('#raw-data-hist-toggle').click(function(){
        $('#histogram-raw-data').toggle();
      });

  //  ------------------ BOXPLOT FORM -----------------------------
  hr
  = render partial: 'chart_queries/form'

  //  ------------------ BOXPLOTS -----------------------------
  - @boxplots.each do |name, boxplot|
    .boxplot
      .card id="parent-for-#{boxplot[:name_code]}"
          == render partial: 'chart_settings', locals: { parent_id: "parent-for-#{boxplot[:name_code]}", chart_id: boxplot[:name_code] }
          .card-header
            strong = name
            .card-actions
              a.settings Settings
              a.download Save
              = link_to 'Del', chart_query_path(boxplot[:id]), method: :delete, class: 'delete'
          .card-body style="position: relative; height:340px;"

      button id="data-toggle-for-#{boxplot[:name_code]}" = t(:ci_table)
      div id="raw-data-for-#{boxplot[:name_code]}" style="display: none;"
        - labels = [:orig_mean, :lower, :upper, :median]
        table.u-full-width.row-header
          tr
            th.header
            th.header
            - boxplot[:header_row].each do |header|
              th = header

          - boxplot[:raw_data].each do |name, row|
            tr
              td.header(rowspan=labels.size+1) = name
              td.header = t(:geo_mean)
              - row.each do |item|
                td = item[:geo_mean]

            - labels.each do |label|
              tr
                td.header = t(label)
                - row.each do |item|
                  td = item[label]

      javascript:
        var boxplotData = #{{ JSON.dump(boxplot[:data]) }};
        drawBoxplot(boxplotData, "#{boxplot[:name_code]}", #{boxplot[:max]});

- else
  p.no-content No data.